### Get all options
GET http://localhost:3000/option
Accept: application/json

### Get all candidates
GET http://localhost:3000/candidate
Accept: application/json

### Update Candidate
PUT http://localhost:3000/candidate/4368
Accept: application/json


### Get all filiers
GET http://localhost:3000/filiere
Accept: application/json

### Create a filiere
POST http://localhost:3000/option
Accept: application/json
Content-Type: application/json

### Create a region
POST http://localhost:3000/region
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "libelle": "Sud-Ouest"
}

### Update a filiere
PUT http://localhost:3000/filiere/1
Accept: application/json
Content-Type: application/json

{
  "libelle": "Mécanique du matériel"
}

### Delete a filiere
DELETE http://localhost:3000/filiere/2
Accept: application/json
Content-Type: application/json
